title: Web java.czechitas.cz
markdown: kramdown
encoding: utf-8
exclude: [.idea, .vscode]
includes_dir: "/"

defaults:
  - scope:
      path: "2019-jaro/java2"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2019-podzim/java1"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-jaro/java-2"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-jaro/java-1"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-podzim/java-1-praha"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-podzim/java-1-ceske-budejovice"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-podzim/git-ceske-budejovice"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-podzim/java-1-brno"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-podzim/java-online"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2021-jaro/java-2"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:categories/:title:output_ext"
      layout: null
