title: Java-Web
markdown: kramdown

defaults:
  - scope:
      path: "2019-jaro/java2"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2019-podzim/java1"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-jaro/java-2"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-jaro/java-1"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-podzim/java-1-praha"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: "2020-podzim/java-1-brno"
      type: "posts"
    values:
      layout: default-post
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:categories/:title:output_ext"
      layout: null
